# ===========================================
# Site Settings
# ===========================================
# Header
site_title: 
site_description: 
# ---Optional ---
site_avatar: 
artical_license_statement: 
# ---End Optional ---
# 避免重复
# menu:
  # Home: /
  # Archives: /archives
  # AboutMe: /about

# display widgets
# 避免冲突
# widgets:
# - archives
# - search
#- social_links
# - recent_posts
# - tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
# baidu_analytics: 542b4962c3c4035fce9071b7c665f0d2
# Google Analytics
# google_analytics: UA-97838175-1
# addthis_analytics: ra-5d3d630390ef40ae
# Disqus
disqus:
  enable: true
  shortname: troyyang-com
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname: troyyang
# Visitors
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 
  server_url: 
donation:
  enable: true
  alipay: 
  wechat: 

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
infinite:
  enable: false
  # title1: 
  # title2: 
